name: Build DYLIB

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: make all
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: libTSSSDKHook
          path: build/dylib/*.dylib
